#!/bin/bash

Annonces=~/Screen/Annonces
s_Annonces=~/Screen/Screen/Annonces
Images=~/Screen/Images
s_Images=~/Screen/Screen/Images

p_web='file:///home/pi/Screen/Horloge/Widget%20Horloge.html'
#p_web='http://vt.unilim.fr/iutmp_rasp_board.html'

t_afich_image=5		# temp d'affichage de chaque image
t_ref=120			# periode de renuvelemen des images dans le partage

navigateur=false

feh_opt="-xqYFZz" #F

if ! [ -d ~/Screen/Screen ]; then
	mkdir ~/Screen/Screen
fi

if ! [ -d $Annonces ]; then
	mkdir $Annonces
fi

if ! [  -d $Images ]; then
	mkdir $Images
fi

rm $Annonces/* 2> /dev/null
rm $Images/* 2> /dev/null

if [ $(mount | grep -c ~/Screen/Screen) = "0" ] 
	then
		sudo mount -t cifs -o username=iutmp-screen,password=Al1-Bab@,domain=iut.ad.unilim.fr //ubox/PEDAGO-IUT/MP/echanges/iutmp-screen /home/pi/Screen/Screen
fi

fich_a_s=$(ls -1 $s_Annonces --file-type | grep -e .jpg -e .png ) 2> /dev/null

if [ -n "$fich_a_s" ]; then
	fich_a_l=$(ls -1 $Annonces --file-type | grep -e .jpg -e .png ) 2> /dev/null
	if [ "$fich_a_s" != "$fich_a_l" ];then
		rm $Annonces/* 2> /dev/null
		cp $s_Annonces/{*.jpg,*.png} $Annonces 2> /dev/null
		feh $feh_opt -D $t_afich_image $Annonces &
	else
		feh $feh_opt -D $t_afich_image $Annonces &
		navigateur=false
	fi
			
else
	fich_i_s=$(ls -1 $s_Images --file-type | grep -e .jpg -e .png ) 2> /dev/null
	if [ -n "$fich_i_s" ]; then
		fich_i_l=$(ls -1 $Images --file-type | grep -e .jpg -e .png ) 2> /dev/null
		if [ "$fich_i_s" != "$fich_i_l" ];then
			rm $Images/* 2> /dev/null
			cp $s_Images/{*.jpg,*.png} $Annonces 2> /dev/null
			feh $feh_opt -D $t_afich_image $Images &
			navigateur=false
		else
			feh $feh_opt -D $t_afich_image $Images &
			navigateur=false
		fi
	else
		chromium-browser --incognito --disable-infobars --disable-suggestions-service --disable-save-password-bubble --start-maximized --kiosk $p_web &
		navigateur=true
	fi
fi

fich_a=$fich_a_s

keypress=''

if [ -t 0 ]; then stty -echo -icanon -icrnl time 0 min 0; fi

while [ "$keypress" != "x" ]; do
	keypress="`cat -v`"

	if [ $(mount | grep -c ~/Screen/Screen) = "0" ] 
	then
		sudo mount -t cifs -o username=iutmp-screen,password=Al1-Bab@,domain=iut.ad.unilim.fr //ubox/PEDAGO-IUT/MP/echanges/iutmp-screen /home/pi/Screen/Screen
	fi

	fich_a_s=$(ls -1 $s_Annonces --file-type | grep -e .jpg -e .png ) 2> /dev/null

	if [ -n "$fich_a_s" ]; then
		fich_a_l=$(ls -1 $Annonces --file-type | grep -e .jpg -e .png ) 2> /dev/null
		if [ "$fich_a_s" != "$fich_a_l" ];then
			rm $Annonces/* 2> /dev/null
			cp $s_Annonces/{*.jpg,*.png} $Annonces 2> /dev/null
			pkill chromium
			pkill feh
			feh $feh_opt -D $t_afich_image $Annonces &
			navigateur=false
		fi
		
	else
		
		fich_i_s=$(ls -1 $s_Images --file-type | grep -e .jpg -e .png ) 2> /dev/null
		if [ -n "$fich_i_s" ]; then
			fich_i_l=$(ls -1 $Images --file-type | grep -e .jpg -e .png ) 2> /dev/null
			if [ "$fich_i_s" != "$fich_i_l" ];then
				pkill feh
				rm $Annonces/* 2> /dev/null
				rm $Images/* 2> /dev/null
				cp $s_Images/{*.jpg,*.png} $Images 2> /dev/null
				pkill chromium
				feh $feh_opt -D $t_afich_image $Images &
				navigateur=false
			else
				if [ -n "$fich_a" ]; then
					pkill chromium
					pkill feh
					rm $Annonces/* 2> /dev/null
					feh $feh_opt -D $t_afich_image $Images &
					navigateur=false
				fi
			fi
		else
			if [ $navigateur != true ];then
				pkill feh
				rm $Images/* 2> /dev/null &
				rm $Annonces/* 2> /dev/null &
				chromium-browser --incognito --disable-infobars --disable-suggestions-service --disable-save-password-bubble --start-maximized --kiosk $p_web &
				navigateur=true
			fi
		fi
	fi

	fich_a=$fich_a_s
	sleep $t_ref
done
if [ -t 0 ]; then stty sane; fi
pkill chromium
pkill feh
rm $Images/* 2> /dev/null
rm $Annonces/* 2> /dev/null
exit